### ISSUE TITLE
Bot.send在某些情况下出了问题

### ISSUE THREAD

**Issue by eya46** [nonebot/adapter-onebot#103]
机器人私聊的情况下触发自身指令，然后发送消息
> 这时候user_id是机器人的id，target_id才是对话的用户

导致消息会发给机器人自己，而不是对话的用户

不确定是不是bug

**Comment by eya46** [comment]
onebot v11

**Comment by yanyongyu** [comment]
请你注意协议端是否配置了上报自身事件，与nonebot无关

**Comment by eya46** [comment]
好像确实不是nb问题，ob协议没这个
机器人发的私聊消息 拉格朗分不出来，gocq是message_sent里面塞target_id
