### ISSUE TITLE
Bug: OneBot V11 和 V12 适配器均使用 `ONEBOT_WS_URLS` 配置导致报错

### ISSUE THREAD

**Issue by This-is-XiaoDeng** [nonebot/adapter-onebot#106]
在同时加载 OneBot V11 和 OneBot V12 适配器时，两个适配器都会对 `ONEBOT_WS_URLS` 配置的 URL 发起连接。

按照 [文档](https://onebot.adapters.nonebot.dev/docs/guide/setup/#%E6%AD%A3%E5%90%91-websocket-%E8%BF%9E%E6%8E%A5-1)，OneBot V12 适配器应该读取 `ONEBOT_V12_WS_URLS` 配置，而不是 `ONEBOT_WS_URLS` 配置。

以下是相关配置及截图：

<details>
<summary>.env 文件</summary>

```env
HOST="0.0.0.0"
ALCONNA_USE_COMMAND_START=True
DRIVER=~fastapi+~httpx+~websockets
PORT=13576
LOG_LEVEL=DEBUG
COMMAND_START=["!"]
SUPERUSERS=["1744793737"]
ONEBOT_ACCESS_TOKEN="xdbot2@xiaodeng_114514"
ONEBOT_WS_URLS=["ws://127.0.0.1:3001"]
```
</details>

<details>
<summary>pyproject.toml 中的 tool.nonebot 节</summary>

```toml
[tool.nonebot]
adapters = [
    { name = "OneBot V12", module_name = "nonebot.adapters.onebot.v12" },
    { name = "OneBot V11", module_name = "nonebot.adapters.onebot.v11" },
]
plugins = [
    "nonebot_plugin_orm",
    "nonebot_plugin_alconna",
    "nonebot_plugin_picstatus",
    "nonebot_plugin_htmlrender",
    "nonebot_plugin_apscheduler",
    "nonebot_plugin_session",
]
plugin_dirs = ["src/plugins"]
builtin_plugins = []
```
</details>

<details>
<summary>相关日志</summary>

![图片](https://github.com/nonebot/adapter-onebot/assets/104149371/9a3156ad-a1c7-425b-848d-61fe9b417c58)
</details>

<details>
<summary>环境</summary>

![图片](https://github.com/nonebot/adapter-onebot/assets/104149371/15b34b0f-f94d-4b80-9c9b-a985bc5d753c)
![图片](https://github.com/nonebot/adapter-onebot/assets/104149371/4e72efb7-b37b-4985-84ed-8c3a4a092a1a)
![图片](https://github.com/nonebot/adapter-onebot/assets/104149371/5b303123-3d34-4d1e-8354-73573ac379f9)
</details>

**Comment by yanyongyu** [comment]
设计就是这么设计的，为了方便所以可以简写，如果你要同时使用两个适配器，你就不应该简写
