### ISSUE TITLE
qq机器人就是没反应，/echo之后不返回任何指令

### ISSUE THREAD

**Issue by qingyunyanran** [nonebot/adapter-onebot#111]
![image](https://github.com/user-attachments/assets/b56750a7-e4ad-4c4e-978b-8d9e222609d4)

**Comment by yanyongyu** [comment]
你的机器人并没有连上nb，你的配置文件填写也是错误的，DRIVER 部分只需要 fastapi，最后的那个dict也不应该存在，另外你还需要加载适配器 OneBot V11
