### ISSUE TITLE
extract_image_urls 获取图片路径不完整

### ISSUE THREAD

**Issue by VAHua** [nonebot/adapter-onebot#117]
![2c9a1925d2ea645ae2825936e7567261](https://github.com/user-attachments/assets/51ff9f20-8ddb-4475-810c-c264d017318f)
&后面的参数没有获取到
![dc484d44255cb084de0c8a83e296c0e1](https://github.com/user-attachments/assets/9d3d9ccd-0c78-4747-871a-b31be55796ce)
这个是完整的链接
![831d17515b3dd6b941655628ce6e82a6](https://github.com/user-attachments/assets/091b44fe-811f-4bdf-ab66-10bd7469d8b9)

**Comment by yanyongyu** [comment]
你的 ob 适配器版本是？另外请你查看下上报的事件内容，这种情况通常是由于协议端使用了string格式上报且内容转义存在错误。

**Comment by yanyongyu** [comment]
如果依然存在问题，请提供详细的事件内容。通常这种问题首先排查协议端问题，nb的ob适配器已经稳定多年，一般不会存在这种低级问题。
