### ISSUE TITLE
引用仅包含@的消息时出现 `AttributeError`

### ISSUE THREAD

**Issue by wling-art** [nonebot/adapter-onebot#118]
**描述**：  
当在QQ中引用一个仅包含@的消息时，处理该引用消息时会出现`NoneType`错误。具体表现为，在[`src/plugins/aichat/__init__.py`](https://github.com/whiTeLeaf-TL/U1bot/blob/main/src/plugins/aichat/__init__.py#L162C5-L162C44)尝试获取`event.message`时，该值为`None`，导致后续的`escape`函数在执行`replace`操作时发生`AttributeError`。

**错误回溯**：
```
10-14 08:29:47 [ERROR] nonebot | Running Matcher(type='message', module=src.plugins.aichat, lineno=63) failed.
Traceback (most recent call last):
  ...
  File "/root/.cache/pypoetry/virtualenvs/u1bot-1qZ_NDF8-py3.11/lib/python3.11/site-packages/nonebot/adapters/onebot/v11/message.py", line 35, in __str__
    return escape(self.data.get("text", ""), escape_comma=False)
  File "/root/.cache/pypoetry/virtualenvs/u1bot-1qZ_NDF8-py3.11/lib/python3.11/site-packages/nonebot/adapters/onebot/v11/utils.py", line 24, in escape
    s = s.replace("&", "&amp;").replace("[", "&#91;").replace("]", "&#93;")
AttributeError: 'NoneType' object has no attribute 'replace'
```

**复现步骤**：
1. 在QQ中发送一条仅包含@消息。
2. 引用这条仅包含@信息

**预期行为**：  
代码应当能够正确处理仅包含@的消息，避免在 `event.message 为 `None` 时引发错误，返回cq码

**Comment by yanyongyu** [comment]
没看出来你的问题是什么导致的，看上去是message里有一个segment的text是None，这个问题是协议端上报数据有问题吧，你使用的是string上报还是array上报？

**Comment by wling-art** [comment]
> 没看出来你的问题是什么导致的，看上去是message里有一个segment的text是None，这个问题是协议端上报数据有问题吧，你使用的是string上报还是array上报？

array上报
用的是lagrangedec docker作为协议端

**Comment by yanyongyu** [comment]
看下original message里每一个segment的数据，如果存在None那就是协议端有问题。

**Comment by wling-art** [comment]
> 看下original message里每一个segment的数据，如果存在None那就是协议端有问题。可以 `repr(event.orignal_message)` 看下。

我看是有的，具体表现是提取Reply的message会出问题
单独的一个信息只有@没有问题，但是引用就会出现None的报错
![image](https://github.com/user-attachments/assets/f50de1d6-a174-45a8-bcbf-f04a380d550a)

**Comment by yanyongyu** [comment]
那 `repr(event.message)` 的内容是啥样的

**Comment by wling-art** [comment]
> 那 `repr(event.message)` 的内容是啥样的

![image](https://github.com/user-attachments/assets/e49980f4-9558-4243-b7d7-12e2f6c107e5)
第一个是GroupMessageEvent的，第二个是Reply的

**Comment by yanyongyu** [comment]
所以是你的reply消息内存在None，那也是协议端返回的有问题
