### ISSUE TITLE
关于v12 `MessageEvent` 的 `message`

### ISSUE THREAD

**Issue by MeetWq** [nonebot/adapter-onebot#15]
nb 去掉了 昵称 和 首尾的 @机器人，而 v12 的 `MessageEvent` 又没有 `raw_message` 字段，
是否应该添加 `raw_message` 字段，内容为原始的 `message` ？

**Comment by yanyongyu** [comment]
这个可以考虑给v11和v12都加上一个origin_message之类的

**Comment by yanyongyu** [comment]
加了个original_message字段，deepcopy了一份
