### ISSUE TITLE
Bug: 发送私聊消息无法判断消息类型

### ISSUE THREAD

**Issue by MeetWq** [nonebot/adapter-onebot#24]
fc2bfef2eda7c106f14777187de64c23c8aad941 中疑似改错了

https://github.com/nonebot/adapter-onebot/blob/e5356a952f9dc4adc15b673ad7ac0e90ab5b6ec8/nonebot/adapters/onebot/v11/bot.py#L162

应为 `params.get("user_id")`

错误信息：https://github.com/noneplugin/nonebot-plugin-petpet/issues/108

**Comment by yanyongyu** [comment]
确实:joy:
