### ISSUE TITLE
onebot v11 API: set_group_anonymous 无法使用

### ISSUE THREAD

**Issue by ZSXB2468** [nonebot/adapter-onebot#47]
我按着文档写的api，但无法使用。两种调用方法都试过。不知道出了什么问题，请各位大佬指教。
撤回信息和禁言匿名者都可以调用，就是设置匿名开关无法使用。

## 版本：
nb: nonebot cli version 1.0.3
onebot v11
go-cqhttp_windows_amd64，协议ipad：
![20230201220420](https://user-images.githubusercontent.com/62994932/216064481-d3319df5-4e23-4fd6-bce0-d1c5c3a401d3.png)

## 原文档：
![20230201215722](https://user-images.githubusercontent.com/62994932/216062842-a12b0a07-de36-4d53-bdfd-37e7463e9e5c.png)

## 报错：
![20230201215742](https://user-images.githubusercontent.com/62994932/216062915-82f186aa-3b8e-4979-a36e-ee5a003e849a.jpg)

## 代码：
![20230201215813](https://user-images.githubusercontent.com/62994932/216063038-5434a1f4-a511-4088-b564-474e29ce27a8.png)

**Comment by yanyongyu** [comment]
https://docs.go-cqhttp.org/api/#%E7%BE%A4%E7%BB%84%E5%8C%BF%E5%90%8D
