### ISSUE TITLE
Question：在私聊中回复机器人消息会过滤图片

### ISSUE THREAD

**Issue by KotoriKoi** [nonebot/adapter-onebot#50]
相关代码：
```
    try:
        event.reply = Reply.parse_obj(await bot.get_msg(message_id=msg_seg.data["id"]))
        logger.info(f"获取到的回复消息: {event.reply}")
    except Exception as e:
        log("WARNING", f"Error when getting message reply info: {repr(e)}", e)
        return
```
没有任何报错，但是会使私聊中回复机器人消息时event.reply中的图片消息为空，群聊正常
私聊测试：

![image](https://user-images.githubusercontent.com/91445888/216848772-79b15af9-7e7c-466a-a578-ead343cda9ab.png)
![image](https://user-images.githubusercontent.com/91445888/216848779-15619d22-976a-4770-98ff-b22207560cd5.png)

群聊测试：
![image](https://user-images.githubusercontent.com/91445888/216848794-c36fd211-6d32-4e4d-aa2a-4d35dbd5d1b0.png)

**Comment by yanyongyu** [comment]
你可以自行调用get msg获取一下回复消息看看内容，nb没有对消息做过处理，可能是gocq返回的就没有
