### ISSUE TITLE
BUG:取消禁言时，实际参数的类型为NoticeEvent而非GroupBanNoticeEvent

### ISSUE THREAD

**Issue by okashi-ya** [nonebot/adapter-onebot#83]
### 操作系统

Windows

### Python 版本

3.11.16

### NoneBot 版本

2.1.2

### 协议端

openShamrock

### 描述问题

![image](https://github.com/nonebot/adapter-onebot/assets/49012015/e99c8af2-fc27-4259-8422-30adc615c032)
这里执行了取消禁言的操作，此时调用进来发现event的类型是NoticeEvent
期望是其为GroupBanNoticeEvent

### 复现步骤

1.使用on_notice监视事件，并打印event类型
2.解除禁言

### 期望的结果

期望可以识别event为GroupBanNoticeEvent类型

### 截图或日志

见上图

**Comment by yanyongyu** [comment]
如果事件类型退化了，说明是你的协议端发送了不符合规范的事件内容，请提供完整事件内容，建议向协议端提出issue

**Comment by okashi-ya** [comment]
> 如果事件类型退化了，说明是你的协议端发送了不符合规范的事件内容，请提供完整事件内容和日志

12-29 16:51:22 [SUCCESS] nonebot | OneBot V11 2059358246 | [notice.group_ban.ban]: {'time': 1703839882, 'self_id': 2059358246, 'post_type': 'notice', 'notice_type': 'group_ban', 'sub_type': 'ban', 'user_id': 852496245, 'group_id': 821534292, 'operator_id': 2059358246, 'duration': 86400, 'sender_id': 2059358246, 'target_id': 852496245}
12-29 16:51:22 [INFO] nonebot | Event will be handled by Matcher(type='notice', module=plugins.kmrbot-plugin-captions_groups.group_ban.group_ban_handler, lineno=7)
12-29 16:51:23 [INFO] nonebot | Matcher(type='notice', module=plugins.kmrbot-plugin-captions_groups.group_ban.group_ban_handler, lineno=7) running complete
12-29 16:51:23 [SUCCESS] nonebot | OneBot V11 2059358246 | [message.group.normal]: Message 451089248 from 210215127@[群:821534292] 'ADMIN（852496245）被KMRTEST2（2059358246）塞了86400秒的口球'
12-29 16:51:29 [SUCCESS] nonebot | OneBot V11 2059358246 | [notice.group_ban.lift_ban]: {'time': 1703839888, 'self_id': 2059358246, 'post_type': 'notice', 'notice_type': 'group_ban', 'group_id': 821534292, 'sub_type': 'lift_ban', 'user_id': 852496245, 'operator_id': 2059358246, 'sender_id': 2059358246, 'target_id': 852496245}

16:51:29为解除禁言的日志，是notice.group_ban.lift_ban这个类型不对么

**Comment by yanyongyu** [comment]
漏了duration参数

**Comment by okashi-ya** [comment]
> 漏了duration参数，建议给shamrock提issue，解除禁言的duration应该是0

好的，非常感谢！
