### ISSUE TITLE
[Question] 群聊中的戳一戳事件是否应该认为是 GroupMessageEvent ?

### ISSUE THREAD

**Issue by SherkeyXD** [nonebot/adapter-onebot#92]
如题 现在对戳一戳消息使用 `isinstance(event, GroupMessageEvent)` 会得到 `False`
这是预期的结果吗

**Comment by SherkeyXD** [comment]
似乎是因为戳一戳事件返回的 event 中不包含 `message_type`，而 isinstance 的判断要求为：
```python
message_type: Literal["group"]
group_id: int
anonymous: Optional[Anonymous] = None
```

**Comment by yanyongyu** [comment]
请提供你的event完整数据

**Comment by SherkeyXD** [comment]
```jsonc
// [notice.notify.poke]
{
  "time": 1707834581,
  "self_id": ***,
  "post_type": "notice",
  "notice_type": "notify",
  "sub_type": "poke",
  "user_id": ***,
  "group_id": ***,
  "target_id": ***,
  "sender_id": ***
}
```

**Comment by SherkeyXD** [comment]
又或许这个问题应该改为： 是否应该添加一个通用的 `GroupNoticeEvent`？
目前的 notice 相关 event 都是以 `Group[...]NoticeEvent` 存在的

**Comment by yanyongyu** [comment]
这个事件是PokeNotifyEvent事件，你可以直接用这个类来判断

**Comment by SherkeyXD** [comment]
主要是我想实现只对群聊的戳一戳做反应，判断完是戳一戳时间之后还要判断来源 但是用 permission.GROUP 没能正常生效 所以就想到了 GroupMessageEvent 这边

**Comment by yanyongyu** [comment]
你可以自己写一个rule来进行判断

**Comment by SherkeyXD** [comment]
我已经写完了（
现在的问题是 `permission.GROUP` 并不能匹配所有来自群聊的消息
或许应该改为检测 `group_id is not None` ？

**Comment by yanyongyu** [comment]
因为 notice event 并不区分群还是好友所以你需要自行判断
