### ISSUE TITLE
Bug: 配置项无法使用 `ONEBOT_ACCESS_TOKEN`

### ISSUE THREAD

**Issue by A-n-k-a** [nonebot/adapter-onebot#94]
文档原文为`ONEBOT_ACCESS_TOKEN=你的访问令牌`
通过阅读代码得知正确配置应为`ONEBOT_V12_ACCESS_TOKEN=你的访问令牌`

**Comment by yanyongyu** [comment]
pydantic是两个名称都应该生效的

**Comment by A-n-k-a** [comment]
我实际使用时发现如果填写`ONEBOT_ACCESS_TOKEN=你的访问令牌`，相当于未设置令牌，只有`ONEBOT_V12_ACCESS_TOKEN=你的访问令牌`才会传递认证令牌。

**Comment by yanyongyu** [comment]
你使用的pydantic版本是？

**Comment by yanyongyu** [comment]
看上去可能是缺了populate by name配置

**Comment by A-n-k-a** [comment]
我使用的pydantic版本是1.10
