### ISSUE TITLE
[SUGGEST?] MessageSegment.node的id传递值应该为int

### ISSUE THREAD

**Issue by ishkong** [nonebot/adapter-onebot#95]
https://github.com/nonebot/adapter-onebot/blob/e05d92c05c7b284f1b2aa925af088082365863a0/nonebot/adapters/onebot/v11/message.py#L177
[gocq文档](https://docs.go-cqhttp.org/cqcode/#%E5%90%88%E5%B9%B6%E8%BD%AC%E5%8F%91%E6%B6%88%E6%81%AF%E8%8A%82%E7%82%B9)中传递的是`int32`
[openshamrock文档](https://whitechi73.github.io/OpenShamrock/message/advanced.html#%E5%90%88%E5%B9%B6%E8%BD%AC%E5%8F%91-%E8%8A%82%E7%82%B9)中传递的是`int64`
是否应该将此处的str删除更合适？

**Comment by yanyongyu** [comment]
[onebot v11 文档](https://github.com/botuniverse/onebot-11/blob/master/message/segment.md#%E5%90%88%E5%B9%B6%E8%BD%AC%E5%8F%91-)这里类型是str

**Comment by ishkong** [comment]
emmm
https://github.com/nonebot/adapter-onebot/blob/e05d92c05c7b284f1b2aa925af088082365863a0/nonebot/adapters/onebot/v11/message.py#L176
那这里提示类型还要用int吗？

**Comment by ishkong** [comment]
并且根据[onebot v11文档](https://github.com/botuniverse/onebot-11/blob/master/message/segment.md#%E9%9F%B3%E4%B9%90%E5%88%86%E4%BA%AB-)
https://github.com/nonebot/adapter-onebot/blob/e05d92c05c7b284f1b2aa925af088082365863a0/nonebot/adapters/onebot/v11/message.py#L152
此处也应该转换为str

**Comment by yanyongyu** [comment]
> 目前，除了合并转发相关的特殊消息段外，几乎所有消息段参数值类型均为字符串，以支持与 CQ 码的相互转换。

似乎应该改成int

**Comment by yanyongyu** [comment]
和别的协议端确认了一下这里应该是str，应该协议端那边适配

**Comment by ishkong** [comment]
好吧，另外拉格朗日可以使用forward发送自行构造合并转发消息了
https://github.com/nonebot/adapter-onebot/blob/8151707aa08a7f7b25283d41b6a9fd3e698ce86f/nonebot/adapters/onebot/v11/message.py#L105
这个提示可以考虑修改一下了

**Comment by yanyongyu** [comment]
改掉了
